### ISSUE TITLE
Circular dependency on python-etils via python-jaxlib provides

### ISSUE THREAD

**Issue by 65a** [brianrobt/python-jax-rocm#1]
This package currently has a circular dep on python-etils which depends on python-jaxlib which this package provides.

**Comment by wuxxin** [comment]
I am sorry, i don't use this package anymore,
@acxz should we make it for adoption in aur ?

**Comment by acxz** [comment]
Even if you aren't using this package anymore, it is still part of the rocm related packages on Arch Linux so we should still keep the repo here. If you don't want to maintain it anymore, you can make me the maintainer for the package on the AUR and I can remove your privileges to this repo.

I'll pick up maintenance in a limited sense and if someone that contributes enough/shows interest in maintenance I'll give them access to both this repo and maintenance of the AUR package.

**Comment by acxz** [comment]
Note: even if you aren't using this package, but still think you can give some time to it, feel free to stick around.

**Comment by wuxxin** [comment]
ok, i will give it a try in the next days to update it, and remove the circular dep.

**Comment by acxz** [comment]
@wuxxin seems like you have removed yourself from maintainership on the AUR for this package. As such I've removed your collaborative status for this repo. Let me know when you want maintainer privileges back.

**Comment by acxz** [comment]
Closed with [cfbf74f](https://github.com/rocm-arch/python-jax-rocm/commit/cfbf74fe65d423043e7af54e90d6971d2ec00526)

**Comment by wuxxin** [comment]
@acxz i agree to disagree, watching debian packages getting bitrotten over and over because of inactive maintainers, i strongly believe in the arch AUR mechanism, where "flagging for adoption", "adoption of unmaintained" is encouraging a fast handover from one community member to another, and i think it ultimately benefits the software quality of the packages.

Also, the order of things happening was: read into the issue, remove myself from owners, realize that you are co-maintainer, asking you to step in or free up for adoption, investing time again to rebuild it, writing down issues found with the new version, getting suspended to write to rocm-arch.

This accidentally also disabled write access to the python-torchvision-rocm package build, which i maintained since 2022 and done over 20 commits and resolved over 20 issues in this time.

I therefore moved the package source to https://github.com/wuxxin/aur-packages and removed you from co-maintainer.
